# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180115_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='similarUsers',
            field=models.ManyToManyField(to='book.Profile'),
        ),
    ]
