# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_profile_similarusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='similarUsers',
            field=models.ManyToManyField(related_name='similarTo', to='book.Profile'),
        ),
    ]
