# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180115_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('clas', 'Classic'), ('fict', 'Fiction'), ('erot', 'Erotica'), ('hist', 'History'), ('dram', 'Drama')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
