# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180116_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('clas', 'Classic'), ('fict', 'Fiction'), ('erot', 'Erotica'), ('hist', 'History'), ('dram', 'Drama'), ('polt', 'Politics'), ('thrl', 'Thriler')], max_length=20),
        ),
    ]
