# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20180116_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='readBooks',
            field=models.ManyToManyField(related_name='readBy', to='book.Book'),
        ),
    ]
