# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20180116_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='book.Profile'),
        ),
    ]
