# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20180117_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='readBooks',
        ),
        migrations.AddField(
            model_name='profile',
            name='dislikedBooks',
            field=models.ManyToManyField(related_name='dislikedBy', to='book.Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likedBooks',
            field=models.ManyToManyField(related_name='likedBy', to='book.Book'),
        ),
    ]
