# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20180117_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Classic', 'clas'), ('Fiction', 'fict'), ('Romance', 'rmnc'), ('History', 'hist'), ('Drama', 'dram'), ('Politics', 'polt'), ('Thriler', 'thrl')], max_length=20),
        ),
    ]
