# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20180117_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Fiction', 'Fiction'), ('Romance', 'Romance'), ('History', 'History'), ('Drama', 'Drama'), ('Politics', 'Politics'), ('Thriler', 'Thriler')], max_length=20),
        ),
    ]
