# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20180117_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Fiction', 'Fiction'), ('Romance', 'Romance'), ('History', 'History'), ('Drama', 'Drama'), ('Politics', 'Politics'), ('Thriler', 'Thriler'), ('Poetry', 'Poetry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dislikedBooks',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='dislikedBy', to='book.Book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='likedBooks',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='likedBy', to='book.Book'),
        ),
    ]
