# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20180117_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='similarUsers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='similarTo', to='book.Profile'),
        ),
    ]
