# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20180117_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommendedBooks',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='recommendedTo', to='book.Book'),
        ),
    ]
